version: '3.0'
networks:
  docker-network:
    driver: bridge
services:
  alb-php-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "docker-alb-php-web"
    working_dir: "/var/www/html"
    volumes:
      - "../src:/var/www/html"
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "9900:9000"
    networks:
      - docker-network
  alb-web:
    image: nginx:stable-alpine
    container_name: "docker-alb-web"
    restart: unless-stopped
    working_dir: "/var/www/html"
    ports:
      - "9085:80"
    volumes:
      - "../src:/var/www/html"
      - "./nginx/web/logs:/var/log/nginx"
      - "./nginx/web/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - alb-php-web
      - alb-mysql
    links:
      - alb-mysql
    networks:
      - docker-network
  alb-mysql:
    image: mysql:8.0.25
    container_name: "docker-alb-mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    volumes:
      - "./~mysql/dbdata:/var/lib/mysql"
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "docker"
      SERVICE_TAGS: dev
      SERVICE_NAME: alb-mysql
    networks:
      - docker-network